; Script initially generated by the Inno Setup Script Wizard.
; To be edited with the Inno Setup Compiler

#define AppName "Sharly Chess"
#define AppPublisher "Sharly Chess"
#define AppURL "https://sharly-chess.com"
#define AppExeName "sharly-chess.exe"
#define ImagesDir "src\web\static\images"
#define RegKey "Software\Sharly Chess\Sharly Chess"

; SCRIPT PARAMS
; These constants are passed as params when compiling the script.
; Uncomment in dev to use with Inno Setup Compiler.
; #define AppVersion "5.0.0.dev1" ; must match a version installed in /dist
; #define IsUpdate "yes" ; yes / no
; #define UseSignTool "no" ; yes / no

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D07C0A2A-2EE7-4440-9B69-9D5ABCC6CF98}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={autopf}\{#AppName}
UninstallDisplayIcon={app}\{#AppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
DisableReadyPage=yes
#if IsUpdate == "yes"
  OutputBaseFilename=Sharly Chess Updater {#AppVersion}
#else
  OutputBaseFilename=Sharly Chess Installer {#AppVersion}
#endif
OutputDir=export
SetupIconFile={#ImagesDir}\sharly-chess.ico
SolidCompression=yes

; Wizard style
WizardBackColor="#313334"
WizardImageBackColor="#313334"
WizardImageFile="{#ImagesDir}\sharly-chess-wizard.png"
WizardSmallImageBackColor="#313334"
WizardSmallImageFile="{#ImagesDir}\sharly-chess-wizard-small.png"

WizardSizePercent=100
WizardStyle=modern dark

[Languages]
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "fr"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
#if IsUpdate == "no"
  Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"
#endif

[Files]
#if UseSignTool == "yes"
  Source: "dist\sharly-chess-{#AppVersion}\{#AppExeName}"; Flags: signonce dontcopy
  Source: "dist\sharly-chess-{#AppVersion}\_internal\tools\*.exe"; Flags: signonce dontcopy recursesubdirs
#endif
Source: "dist\sharly-chess-{#AppVersion}\*"; DestDir: "{app}"; Excludes: "\tmp\*"; Flags: ignoreversion recursesubdirs

[Icons]
#if IsUpdate == "no"
  Name: "{autoprograms}\{#AppName}"; Filename: "{app}\{#AppExeName}"
  Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon
#endif

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall

[Registry]
#if IsUpdate == "no"
  Root: HKCU; Subkey: "{#RegKey}"; ValueType: string; ValueName: "data_directory"; ValueData: "{code:GetSelectedDataDir}"; Check: not DataDirExists()
  Root: HKCU; Subkey: "{#RegKey}"; ValueType: string; ValueName: "locale"; ValueData: "{code:GetActiveLanguage}"
#endif

[Code]
var
  DataDirPage: TInputDirWizardPage;

function DataDirExists() : Boolean;
begin
  Result := RegValueExists(HKEY_CURRENT_USER, ExpandConstant('{#RegKey}'), 'data_directory');
end;

procedure InitializeWizard;
begin
  if not DataDirExists() then
  begin
    DataDirPage := CreateInputDirPage(
      wpSelectDir,
      ExpandConstant('{cm:SelectDataLocation}'),
      ExpandConstant('{cm:WhereData}'),
      ExpandConstant('{cm:PleaseSelectData}'),
      False,
      ExpandConstant('{#AppName}')
    );
    DataDirPage.Add('');
    DataDirPage.Values[0] := ExpandConstant('{userdocs}\{#AppName}');
  end;
end;

function GetSelectedDataDir(Param: string) : string;
begin
  Result := DataDirPage.Values[0];
end;

function GetActiveLanguage(Param: string) : string;
begin
  Result := ActiveLanguage();
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if (CurStep = ssPostInstall) and WizardSilent() then
  begin
    MsgBox(ExpandConstant('{cm:UpdateSuccessfull}'), mbInformation, MB_OK);
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID in [wpSelectTasks, wpReady] then
    WizardForm.NextButton.Caption := SetupMessage(msgButtonInstall)
  else if CurPageID = wpFinished then
    WizardForm.NextButton.Caption := SetupMessage(msgButtonFinish)
  else
    WizardForm.NextButton.Caption := SetupMessage(msgButtonNext);
end;


[Messages]
#if IsUpdate == "yes"
    en.SetupAppTitle=Update
    fr.SetupAppTitle=Mise à jour

    en.SetupWindowTitle=Update - %1
    fr.SetupWindowTitle=Mise à jour - %1

    en.WizardInstalling=Updating
    fr.WizardInstalling=Mise à jour

    en.InstallingLabel=Please wait while [name] is updating.
    fr.InstallingLabel=Merci de patienter pendant que [name] se met à jour.

    en.WizardPreparing=Preparing to update
    fr.WizardPreparing=Préparation de la mise à jour

    en.PreparingDesc=The updater is preparing to update [name] on your computer.
    fr.PreparingDesc=L'assistant de mise à jour se prépare à mettre [name] à jour sur votre ordinateur.
#else
    en.InstallingLabel=Please wait while [name] is installing.
    fr.InstallingLabel=Merci de patienter pendant que [name] s'installe.
#endif

en.SelectTasksLabel2=Select the additional tasks you would like to perform while installing [name], then click Install.
fr.SelectTasksLabel2=Sélectionnez les tâches supplémentaires que vous voulez effectuer lors de l'installation de [name], puis cliquez sur Installer.

en.ConfirmUninstall=Are you sure you want to uninstall Sharly Chess?
fr.ConfirmUninstall=Êtes-vous sûr de vouloir désinstaller Sharly Chess ?


[CustomMessages]
en.SelectDataLocation=Select data location
fr.SelectDataLocation=Sélectionner l'emplacement des données

en.WhereData=Where should the data be stored?
fr.WhereData=Où les données doivent-être sauvegardées ?

en.PleaseSelectData=Please select a folder for the data.
fr.PleaseSelectData=Merci de sélectionner un dossier pour les données.

en.UpdateSuccessfull=Sharly Chess was sucessfully updated. The application will restart.
fr.UpdateSuccessfull=Sharly Chess a été mis à jour avec succès. L'application va redémarrer.

en.ShouldDeleteData=Do you also want to delete the application's data?
fr.ShouldDeleteData=Voulez-vous également supprimer les données de l'application ?
