; Script initially generated by the Inno Setup Script Wizard.
; To be edited with the Inno Setup Compiler

#define AppName "Sharly Chess"
#define AppPublisher "Sharly Chess"
#define AppURL "https://sharly-chess.com"
#define AppExeName "sharly-chess.exe"
#define ImagesDir "src\web\static\images"
#define RegKey "Software\Sharly Chess\Sharly Chess"

; SCRIPT PARAMS
; These constants are passed as params when compiling the script.
; Uncomment in dev to use with Inno Setup Compiler.
; #define AppVersion "5.0.0.dev1" ; must match a version installed in /dist
; #define IsUpdate 1 ; 1 = update, 0 = install
; #define UseSignTool "no" ; yes / no

; Default off for local/dev builds; CI passes /DUseSignTool=yes to sign via Inno.
#ifndef UseSignTool
  #define UseSignTool "no"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D07C0A2A-2EE7-4440-9B69-9D5ABCC6CF98}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={autopf}\{#AppName}
UninstallDisplayIcon={app}\{#AppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
DisableReadyPage=yes
#if Int(IsUpdate) == 1
  OutputBaseFilename=sharly-chess-updater-{#AppVersion}
#else
  OutputBaseFilename=sharly-chess-installer-{#AppVersion}
#endif
OutputDir=export
SetupIconFile={#ImagesDir}\sharly-chess.ico
SolidCompression=yes
; When UseSignTool=yes, iscc is called with /Sazuresign=... so Inno signs the
; setup exe AND the generated uninstaller (unins000.exe) via Azure Trusted
; Signing — the one thing the external signing action can't reach.
#if UseSignTool == "yes"
SignTool=azuresign
SignedUninstaller=yes
#endif

; Wizard style
WizardBackColor="#313334"
WizardImageBackColor="#313334"
WizardImageFile="{#ImagesDir}\sharly-chess-wizard.png"
WizardSmallImageBackColor="#313334"
WizardSmallImageFile="{#ImagesDir}\sharly-chess-wizard-small.png"

WizardSizePercent=100
WizardStyle=modern dark

[Languages]
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "fr"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
#if Int(IsUpdate) == 0
  Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"
  Name: "defenderprogram"; Description: "{cm:DefenderProgram}"; GroupDescription: "{cm:DefenderGroup}"; Check: GetIsDefenderActive()
  Name: "defenderdata"; Description: "{cm:DefenderData}"; GroupDescription: "{cm:DefenderGroup}"; Check: GetIsDefenderActive()
#endif

[InstallDelete]
; Remove previous *.dist-info before copying the new files. These folders are
; version-named (e.g. sharly_chess-5.0.0a4.dist-info), and Inno only overwrites
; same-named files, so stale ones from the old version pile up in _internal and
; importlib.metadata could then read the wrong version for the app or a
; dependency. Runs before [Files], which rewrites the current ones.
Type: filesandordirs; Name: "{app}\_internal\*.dist-info"

[Files]
#if UseSignTool == "yes"
  Source: "dist\sharly-chess-{#AppVersion}\{#AppExeName}"; Flags: signonce dontcopy
  Source: "dist\sharly-chess-{#AppVersion}\_internal\tools\*.exe"; Flags: signonce dontcopy recursesubdirs
#endif
Source: "dist\sharly-chess-{#AppVersion}\*"; DestDir: "{app}"; Excludes: "\tmp\*"; Flags: ignoreversion recursesubdirs

[Icons]
#if Int(IsUpdate) == 0
  Name: "{autoprograms}\{#AppName}"; Filename: "{app}\{#AppExeName}"
  Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon
#endif

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall

[Registry]
#if Int(IsUpdate) == 0
  Root: HKCU; Subkey: "{#RegKey}"; ValueType: string; ValueName: "data_directory"; ValueData: "{code:GetDataDir}"
  Root: HKCU; Subkey: "{#RegKey}"; ValueType: string; ValueName: "locale"; ValueData: "{code:GetActiveLanguage}"
#endif

[Code]
var
  DataDirPage: TInputDirWizardPage;
  DataDir: String;
  IsDefenderActive: Boolean;


function DataDirExists() : Boolean;
begin
  Result := DataDir = '';
end;

procedure InitIsDefenderActive;
var
  ResultCode: Integer;
  Output: TExecOutput;
begin
  ExecAndCaptureOutput(
    'cmd.exe',
    '/C powershell -Command "Get-MpComputerStatus | Select-Object -ExpandProperty AMServiceEnabled"',
    '',
    SW_HIDE,
    ewWaitUntilTerminated,
    ResultCode,
    Output
  );
  if GetArrayLength(Output.StdOut) > 0 then
    IsDefenderActive := Pos('True', Output.StdOut[0]) > 0;
end;

procedure InitDataDir;
begin
  RegQueryStringValue(
    HKEY_CURRENT_USER,
    ExpandConstant('{#RegKey}'),
    'data_directory',
    DataDir
  );
end;

procedure InitializeWizard;
begin
  if {#IsUpdate} = 0 then
  begin
    InitIsDefenderActive();
    InitDataDir();
  end;
  if not DataDirExists() then
  begin
    DataDirPage := CreateInputDirPage(
      wpSelectDir,
      ExpandConstant('{cm:SelectDataLocation}'),
      ExpandConstant('{cm:WhereData}'),
      ExpandConstant('{cm:PleaseSelectData}'),
      False,
      ExpandConstant('{#AppName}')
    );
    DataDirPage.Add('');
    DataDirPage.Values[0] := ExpandConstant('{userdocs}\{#AppName}');
  end;
end;

function ExpandEnvStrings(lpSrc: PAnsiChar; lpDst: PAnsiChar; nSize: Cardinal): Cardinal;
external 'ExpandEnvironmentStringsA@kernel32.dll stdcall';

function GetExpandedPath(const Path: String): String;
var
  Buffer: AnsiString;
begin
  SetLength(Buffer, 1024);
  if ExpandEnvStrings(PAnsiChar(AnsiString(Path)), PAnsiChar(Buffer), 1024) > 0 then
    Result := Buffer
  else
    Result := Path; // Fallback if expansion fails
end;

function GetDataDir(Param: string) : string;
begin
  if DataDirExists() then
    Result := DataDir;
  Result := GetExpandedPath(DataDirPage.Values[0]);
end;

function GetActiveLanguage(Param: string) : string;
begin
  Result := ActiveLanguage();
end;

function GetIsDefenderActive(): Boolean;
begin
  Result := IsDefenderActive;
end;

procedure AddDefenderPathException(Path: string);
var
  ResultCode: Integer;
begin
  Exec(
    'cmd.exe',
    '/C powershell -Command "Add-MpPreference -ExclusionPath """'+ Path + '""" -Force"',
    '',
    SW_HIDE,
    ewWaitUntilTerminated,
    ResultCode
  );
 end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if (CurStep = ssPostInstall) and WizardSilent() then
  begin
    MsgBox(ExpandConstant('{cm:UpdateSuccessfull}'), mbInformation, MB_OK);
  end;
  if CurStep = ssInstall then
  begin
    if WizardIsTaskSelected('defenderprogram') then
      AddDefenderPathException(ExpandConstant('{app}'));
    if WizardIsTaskSelected('defenderdata') then
      AddDefenderPathException(GetDataDir(''));
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID in [wpSelectTasks, wpReady] then
    WizardForm.NextButton.Caption := SetupMessage(msgButtonInstall)
  else if CurPageID = wpFinished then
    WizardForm.NextButton.Caption := SetupMessage(msgButtonFinish)
  else
    WizardForm.NextButton.Caption := SetupMessage(msgButtonNext);
end;

[Messages]
#if Int(IsUpdate) == 1
    en.SetupAppTitle=Update
    fr.SetupAppTitle=Mise à jour

    en.SetupWindowTitle=Update - %1
    fr.SetupWindowTitle=Mise à jour - %1

    en.WizardInstalling=Updating
    fr.WizardInstalling=Mise à jour

    en.InstallingLabel=Please wait while [name] is updating.
    fr.InstallingLabel=Merci de patienter pendant que [name] se met à jour.

    en.WizardPreparing=Preparing to update
    fr.WizardPreparing=Préparation de la mise à jour

    en.PreparingDesc=The updater is preparing to update [name] on your computer.
    fr.PreparingDesc=L'assistant de mise à jour se prépare à mettre [name] à jour sur votre ordinateur.
#else
    en.InstallingLabel=Please wait while [name] is installing.
    fr.InstallingLabel=Merci de patienter pendant que [name] s'installe.
#endif

en.SelectTasksLabel2=Select the additional tasks you would like to perform while installing [name], then click Install.
fr.SelectTasksLabel2=Sélectionnez les tâches supplémentaires que vous voulez effectuer lors de l'installation de [name], puis cliquez sur Installer.

en.ConfirmUninstall=Are you sure you want to uninstall Sharly Chess?
fr.ConfirmUninstall=Êtes-vous sûr de vouloir désinstaller Sharly Chess ?


[CustomMessages]
en.SelectDataLocation=Select data location
fr.SelectDataLocation=Sélectionner l'emplacement des données

en.WhereData=Where should the data be stored?
fr.WhereData=Où les données doivent-être sauvegardées ?

en.PleaseSelectData=Please select a folder for the data.
fr.PleaseSelectData=Merci de sélectionner un dossier pour les données.

en.UpdateSuccessfull=Sharly Chess was sucessfully updated. The application will restart.
fr.UpdateSuccessfull=Sharly Chess a été mis à jour avec succès. L'application va redémarrer.

en.ShouldDeleteData=Do you also want to delete the application's data?
fr.ShouldDeleteData=Voulez-vous également supprimer les données de l'application ?

en.DefenderGroup=Microsoft Defender exception list:
fr.DefenderGroup=Liste d'exclusions Microsoft Defender :

en.DefenderProgram=Add the program folder
fr.DefenderProgram=Ajouter le dossier du programme

en.DefenderData=Add the data folder
fr.DefenderData=Ajouter le dossier des données
