from traceback import extract_stack, StackSummary
import gettext as gettext_lib
import os
import plistlib
import subprocess
import sys
import threading
from gettext import GNUTranslations
from logging import Logger
from pathlib import Path

from common import BASE_DIR, DEVEL_ENV, TEST_ENV
from common.exception import SharlyChessException
from common.i18n.babel_updaters import BabelUpdater
from common.i18n.domains import Domain
from common.logger import get_logger

logger: Logger = get_logger()

# The default locale used when no default locale is set in the configuration file.
DEFAULT_LOCALE: str = 'en'
logger.debug('Default locale: %s', DEFAULT_LOCALE)

# The directory where to find the i18n files for the core of the app.
_core_locale_dir: Path = Domain().locale_dir
logger.debug('Core locale folder: %s', _core_locale_dir)

# Build a dict of all the translations with the available locales retrieved from the filesystem.
locales: list[str] = []
# sort the list to ensure that the order is the same on all the OS
for l_entry in sorted(_core_locale_dir.iterdir()):
    if l_entry.is_dir():
        mo_file: Path = l_entry / 'LC_MESSAGES' / f'{Domain.core_name}.mo'
        if mo_file.is_file():
            locales.append(l_entry.name)
        elif DEVEL_ENV:
            # locales are built on the PO files found if no MO files found
            po_file: Path = l_entry / 'LC_MESSAGES' / f'{Domain.core_name}.po'
            if po_file.is_file():
                locales.append(l_entry.name)
        else:
            raise SharlyChessException(
                f'Invalid locale [{l_entry.name}] (MO file [{mo_file}] not found), exiting.'
            )

_auto_update_file: Path = BASE_DIR / 'src' / 'common' / 'i18n' / '.auto-update'

if DEVEL_ENV:
    babel_updater: BabelUpdater = BabelUpdater(
        Domain.get_domains(),
        locales,
        DEFAULT_LOCALE,
    )
    # if i18n_update is running then update_i18n_files() will be called later,
    # no need to do anything here
    if _auto_update_file.is_file() and Path(sys.argv[0]).stem != 'i18n_update':
        # if the auto-update file is found, build everything needed
        # (depending on the changes of the i18n source files and the POT/PO/MO files)
        # no doc (i18n.mpd) is generated by default,
        # i18n_update.py --generate-doc must be used for that
        babel_updater.update()
    elif Path(sys.argv[0]).stem != 'i18n_update':
        # no need to update the MO files if i18n_update is running
        babel_updater.update_mo_files()
    else:
        # just ensure that the MO files are present (to build _all_translations below)
        babel_updater.create_absent_mo_files()
elif TEST_ENV:
    # When testing, make sure that the MO files will be available (including on GitHub)
    BabelUpdater(
        Domain.get_domains(),
        locales,
        DEFAULT_LOCALE,
    ).create_absent_mo_files()


def update_i18n_files(
    clean: bool,
    generate_doc: bool,
) -> bool:
    """Update all the i18n files if needed, returns False if the translations should be updated, True otherwise."""
    return BabelUpdater(
        Domain.get_domains(),
        locales,
        DEFAULT_LOCALE,
    ).update(
        clean=clean,
        generate_doc=generate_doc,
    )


# now load the translations.
_all_translations: dict[str | None, dict[str, GNUTranslations]] = {}
for domain in Domain.get_domains():
    _all_translations[domain.name] = {}
    for loc in locales:
        try:
            _all_translations[domain.name][loc] = gettext_lib.translation(
                domain.name,
                domain.locale_dir,
                [
                    loc,
                ],
            )
        except Exception as ex:
            raise SharlyChessException(f'Could not load locale [{loc}]: {ex}.')

logger.debug('Locales found: %s', ', '.join(locales))

# Initialize the current thread with the default locale.
_thread_local_data = threading.local()


def get_locale() -> str:
    """Returns the locale of the current thread."""
    try:
        return _thread_local_data.locale
    except AttributeError:
        return DEFAULT_LOCALE


def set_locale(locale: str) -> bool:
    """Sets the locale for the current thread, returns True if the given locale is recognized."""
    if hasattr(_thread_local_data, 'locale') and _thread_local_data.locale == locale:
        return True
    if locale in locales:
        _thread_local_data.locale = locale
        logger.debug('Locale set to [%s].', locale)
        return True
    else:
        logger.warning('Unknown locale [%s].', locale)
        return False


_domain_names: list[str] = [d.name for d in Domain.get_domains()]
_plugins_pattern: str = (
    os.sep
    + os.sep.join(
        [
            'src',
            'plugins',
        ]
    )
    + os.sep
)
_plugins_pattern_len: int = len(_plugins_pattern)
_i18n_pattern: str = (
    os.sep
    + os.sep.join(
        [
            'src',
            'common',
            'i18n',
        ]
    )
    + os.sep
)
_jinja_pattern = os.sep + os.sep.join(['site-packages', 'jinja2']) + os.sep


def get_filename_plugin_name(filename: str) -> str:
    pos: int = filename.rfind(_plugins_pattern)
    if pos != -1:
        relative_path: str = filename[pos + _plugins_pattern_len :]
        plugin_name: str = relative_path.split(os.sep, 1)[0]
        if plugin_name in _domain_names:
            return plugin_name
    return Domain.core_name


def get_i18n_domain() -> str:
    global _domain_names
    search_current_frame: bool = True
    stack_summary: StackSummary = extract_stack()
    for frame_summary in reversed(stack_summary):
        if search_current_frame:
            if frame_summary.name == 'get_i18n_domain':
                search_current_frame = False
                continue
        else:
            # looking for the calling frame (not in this module)
            if (
                frame_summary.filename.rfind(_i18n_pattern) == -1
                and frame_summary.filename.rfind(_jinja_pattern) == -1
            ):
                return get_filename_plugin_name(frame_summary.filename)
    return Domain.core_name


def gettext(message: str, locale: str | None = None):
    """Overrides the gettext.gettext() function to use the locale of the current thread."""
    logger.error(f'gettext([{message}]):')
    for frame_summary in reversed(extract_stack()):
        logger.error(f'{frame_summary=}])')
    logger.error(f'gettext([{get_i18n_domain()=}])')
    if locales:
        return _all_translations[get_i18n_domain()][locale or get_locale()].gettext(
            message
        )
    else:
        return gettext_lib.gettext(message)


def _(message: str, locale: str | None = None):
    """An alias for gettext()."""
    return gettext(message, locale)


def ngettext(singular: str, plural: str, n: int, locale: str | None = None):
    """Overrides the gettext.ngettext() function to use the locale of the current thread."""
    if locales:
        return _all_translations[get_i18n_domain()][locale or get_locale()].ngettext(
            singular, plural, n
        )
    else:
        return gettext_lib.ngettext(singular, plural, n)


def normalize_bcp47_to_locale(tag: str) -> str:
    """
    Convert a BCP47-like tag (e.g. 'en-US', 'pt-BR', 'zh-Hans-CN') to a
    Python locale-ish string. Keeps only language + region when present.
    """
    if not tag:
        return tag
    parts = tag.replace('_', '-').split('-')
    if len(parts) >= 2 and len(parts[1]) in (2, 3):
        return f'{parts[0].lower()}_{parts[1].upper()}'
    # no explicit region; return language only
    return parts[0].lower()


def read_macos_global_prefs() -> dict:
    """
    Read ~/Library/Preferences/.GlobalPreferences.plist as a dict.
    Falls back to `defaults read -g` if needed.
    """
    # Preferred: read the plist directly
    plist_path = os.path.expanduser('~/Library/Preferences/.GlobalPreferences.plist')
    try:
        with open(plist_path, 'rb') as fp:
            return plistlib.load(fp) or {}
    except Exception:
        pass

    # Fallback: `defaults` (returns a legacy-ish format; use `export` for real plist)
    try:
        proc = subprocess.run(
            ['defaults', 'export', '-g', '-'], check=True, capture_output=True
        )
        return plistlib.loads(proc.stdout) or {}
    except Exception:
        return {}
