import argparse
import html
import sys
from datetime import datetime
from pathlib import Path

from common.i18n import _, locales, set_locale
from common.logger import print_interactive_info, print_interactive_error
from data.print_documents.place_cards.template import PlaceCardTemplate
from data.print_documents.place_cards.types import PlaceCardType


def generate_doc(
    output_dir: Path,
):
    templates_by_type: dict[PlaceCardType, list[PlaceCardTemplate]] = (
        PlaceCardTemplate.get_place_card_templates_by_type()
    )
    for locale in locales:
        set_locale(locale)
        output_file: Path = output_dir / f'place-cards-library-{locale}.md'
        print_interactive_info(f'Writing file [{output_file.name}]...')
        with open(output_file, 'w', encoding='utf-8') as f:
            for place_card_type, templates in templates_by_type.items():
                f.write(
                    f'<!-- Do not edit this file manually, use script {Path(__file__).name} instead. -->\n\n'
                )
                for embedded in [
                    True,
                    False,
                ]:
                    for template in templates:
                        if template.embedded == embedded:
                            template_origin: str = (
                                _('embedded in _Sharly Chess_')
                                if embedded
                                else _('example')
                            )
                            template_sub_dir: str = (
                                'src/web/templates/admin/print'
                                if embedded
                                else 'examples/place_cards'
                            )
                            template_download_url: str = f'https://raw.githubusercontent.com/Sharly-Chess/sharly-chess/refs/heads/feature/dev/{template_sub_dir}/place_cards/{template.id}.template'
                            f.write(
                                f'### {place_card_type.static_name()} - {template.name}\n\n'
                            )
                            f.write(template.preview())
                            f.write(
                                f'- {_("Origin: {template_origin}").format(template_origin=template_origin)}\n'
                            )
                            f.write(
                                f'- {_("Creator: {template_creator}").format(template_creator=html.escape(template.creator))}\n'
                            )
                            f.write(
                                f'- {_("Size ({unit}): {width}x{height}").format(unit=template.unit, width=template.width, height=template.height)}\n'
                            )
                            f.write(f'- [{_("Download")}]({template_download_url})\n')
                            f.write('\n')
                f.write(
                    f'<!-- {
                        _("Generated by script {script_name} on {date}").format(
                            script_name=Path(__file__).name,
                            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
                        )
                    } -->\n\n'
                )
    print_interactive_info('Done.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-o',
        '--web-root-dir',
        type=str,
        help='the output directory',
    )
    args = parser.parse_args()
    web_root_dir: Path = Path(args.web_root_dir or '../doc')
    if not args.web_root_dir:
        print_interactive_info(
            f'Option --web-root-dir not set, using [{web_root_dir.resolve()}] by default.'
        )
    doc_output_dir: Path = web_root_dir / 'docs' / 'printing'
    if not doc_output_dir.exists():
        print_interactive_error(
            f'Output directory [{doc_output_dir.resolve()}] not found, exiting.'
        )
        sys.exit(1)
    generate_doc(doc_output_dir)
