"""This module is a utility script to create the papi template.
This script re-creates the papi_template.py file from the template.papi file.
"""

import bz2
import base64
from pathlib import Path

template_path: Path = Path() / 'scripts' / 'papi' / 'template-3.3.8.papi'
output_path = Path() / 'src' / 'database' / 'access' / 'papi' / 'papi_template.py'

if not template_path.exists():
    raise FileNotFoundError(template_path)

with open(output_path, 'wt', encoding='utf-8') as output_file:
    output_file.write(
        f'############################################################################\n'
        f'# This file is generated by {Path(__file__).name}, DO NOT EDIT !!!\n'
        f'############################################################################\n'
        f'import bz2\n'
        f'import base64\n'
        f'from pathlib import Path\n'
        f'\n'
        f'\n'
        'def create_empty_papi_database(file: Path):\n'
    )
    with open(template_path, 'rb') as input_file:
        b64 = base64.b64encode(bz2.compress(input_file.read()))
        output_file.write('    b64 = (\n')
        part_len: int = 80
        for b64_part in [b64[i : i + part_len] for i in range(0, len(b64), part_len)]:
            output_file.write(f'        {b64_part}\n')
    output_file.write('    )\n')
    output_file.write(
        '    file.parent.mkdir(parents=True, exist_ok=True)\n'
        "    with open(file, 'wb') as f:\n"
        '        f.write(bz2.decompress(base64.decodebytes(b64)))\n'
    )
