from datetime import datetime
from pathlib import Path

from common.i18n import _, locales
from common.logger import print_interactive_info, print_interactive_success
from data.auth.actions import AuthActionCategory, AuthAction
from data.auth.managers import RoleManager
from data.auth.roles import Role


def main():
    generated_by: str = _('Generated by script {script_name} on {date}').format(
        script_name=Path(__file__).name,
        date=datetime.now().strftime('%Y-%m-%d %H:%M'),
    )
    print_interactive_info('Generating access levels inheritance documentation...')
    for locale in locales:
        with open(
            output_file := Path(__file__).with_name(
                f'access-levels-inheritance-{locale}.md'
            ),
            'wt',
        ) as output:
            print(
                '|'
                f' {_("Access level").replace(" ", "<br/>")} |'
                f' {_("Scope").replace(" ", "<br/>")} |'
                f' {_("Sub access levels").replace(" ", "<br/>")} |'
                f' {_("Inherited access levels").replace(" ", "<br/>")} |'
                f' {_("Manageable access levels").replace(" ", "<br/>")} |',
                file=output,
            )
            print('|-|:-:|:-:|:-:|:-:|', file=output)
            access_levels: list[Role] = RoleManager.objects()
            for access_level in access_levels:
                ordered_direct_sub_access_levels = [
                    r
                    for r in access_levels
                    if r.__class__ in access_level.direct_sub_roles()
                ]
                ordered_indirect_sub_access_levels = [
                    r
                    for r in access_levels
                    if r in access_level.sub_roles()
                    and r not in ordered_direct_sub_access_levels
                ]
                direct_sub_access_levels_str: str = f'_{_("none")}_'
                if ordered_direct_sub_access_levels:
                    direct_sub_access_levels_str = '<br/>'.join(
                        r.short_name() for r in ordered_direct_sub_access_levels
                    )
                indirect_sub_access_levels_str: str = f'_{_("none")}_'
                if (
                    len(ordered_direct_sub_access_levels)
                    + len(ordered_indirect_sub_access_levels)
                    == len(access_levels) - 1
                ):
                    indirect_sub_access_levels_str = f'_{_("all")}_'
                elif ordered_indirect_sub_access_levels:
                    indirect_sub_access_levels_str = '<br/>'.join(
                        r.short_name() for r in ordered_indirect_sub_access_levels
                    )
                manageable_access_levels_str: str = f'_{_("none")}_'
                ordered_manageable_access_levels: list[Role] = [
                    r
                    for r in RoleManager.objects()
                    if r in access_level.manageable_roles()
                ]
                if len(ordered_manageable_access_levels) == len(access_levels) - 1:
                    manageable_access_levels_str = f'_{_("all")}_'
                elif ordered_manageable_access_levels:
                    manageable_access_levels_str = '<br/>'.join(
                        r.short_name() for r in ordered_manageable_access_levels
                    )
                print(
                    f'|{access_level.short_name()}: {access_level.name}|{access_level.scope.name}|{direct_sub_access_levels_str}|{indirect_sub_access_levels_str}|{manageable_access_levels_str}|',
                    file=output,
                )
            print(f'\n_{generated_by}_', file=output)
        print_interactive_success(
            f'Access levels inheritance written to {output_file}.'
        )

    actions_by_category: dict[AuthActionCategory, list[AuthAction]] = {}
    for category in AuthActionCategory.categories():
        actions_by_category[category] = []
    for action in AuthAction.actions():
        actions_by_category[action.category].append(action)

    print_interactive_info('Generating permissions by access level documentation...')
    for locale in locales:
        with open(
            output_file := Path(__file__).with_name(
                f'access-levels-permissions-{locale}.md'
            ),
            'wt',
        ) as output:
            mark_ok = ':white_check_mark:'
            mark_ko = ':x:'
            mark_na = ':white_circle:'
            col1_size = max(len(action.name) for action in AuthAction.actions())
            col_size = max(
                max(len(access_level.short_name()) for access_level in access_levels),
                max(len(mark) for mark in (mark_ok, mark_ko, mark_na)) + 3,
            )  # 3 = len('(*)')

            def print_line(col1: str, cols: list[str], last_col: str):
                print(
                    '|'
                    f' {col1.ljust(col1_size)} |'
                    f' {" | ".join([col.ljust(col_size) for col in cols] + [last_col.ljust(col_size)])} |',
                    file=output,
                )

            def print_header(col1: str, last_col: str):
                print_line(
                    col1,
                    [r.short_name().ljust(col_size) for r in access_levels],
                    last_col,
                )

            print_line(
                _('Permissions / Access levels'),
                [
                    '',
                ]
                * len(access_levels),
                '',
            )
            print(
                f'|-{"-" * col1_size}-|{f":{'-' * col_size}:|" * (len(access_levels) + 1)}',
                file=output,
            )
            for category, actions in actions_by_category.items():
                print_header(category.name.upper(), f'_{_("none")}_')
                if category == AuthActionCategory.EVENTS_ACCESS:
                    print_line(
                        _('View public current events'),
                        [
                            mark_ok,
                        ]
                        + [
                            mark_na,
                        ]
                        * (len(access_levels) - 1),
                        f'{mark_ok}(*)',
                    )
                for action in actions_by_category[category]:
                    if category in [
                        AuthActionCategory.APPLICATION,
                        AuthActionCategory.EVENTS_ACCESS,
                    ]:
                        print_line(
                            action.name,
                            [
                                mark_ok
                                if action in access_levels[0].allowed_actions()
                                else mark_ko,
                            ]
                            + [
                                mark_na,
                            ]
                            * (len(access_levels) - 1),
                            mark_ko,
                        )
                    else:
                        print_line(
                            action.name,
                            [
                                (
                                    mark_ok
                                    if action in access_level.allowed_actions()
                                    else mark_ko
                                )
                                for access_level in access_levels
                            ],
                            mark_ko,
                        )
                if category == AuthActionCategory.ACCESS:
                    for access_level in access_levels:
                        print_line(
                            _(
                                'Give/take away access level {access_level_short_name}'
                            ).format(access_level_short_name=access_level.short_name()),
                            [
                                (
                                    mark_ok
                                    if access_level in access_level2.manageable_roles()
                                    else mark_ko
                                )
                                for access_level2 in access_levels
                            ],
                            mark_ko,
                        )
            print(f'\n_{generated_by}_', file=output)
        print_interactive_success(
            f'Access levels permissions written to {output_file}.'
        )
    print_interactive_info('Done.')


if __name__ == '__main__':
    main()
