"""Have the other engine's checker verify the tournaments we generate.

The check-list asks (C.04.A Annex 3, question 33) whether the pairing and
tie-break engines "have been tested against another publicly available
pairing and tie-break engine, with at least 50,000 random tournaments
generated by the RTG of each engine and verified by the PTC of the other
engine", and calls it "a mandatory test for the THP's PTC and RTG".

This is the direction where we generate and Gacrux checks. Each tournament
is written by our generator and handed to both of Gacrux's checkers: the
pairing checker re-pairs every round, and the tie-break checker recomputes
the standings from the criteria the file names. A tournament either of them
refuses is a disagreement between the two programs on a position neither
of us chose, which is the whole point of asking somebody else.

The other direction -- Gacrux generates, we check -- is
``scripts/gacrux/corpus.py``, over the tournaments its author publishes.

    PYTHONPATH=src:. ./venv/bin/python scripts/fide/cross_check.py 50000 --jobs 8

Each worker generates in a directory of its own under the report
directory, so nothing here touches ``tests/tmp`` and a test run alongside
it is harmless. Findings are one JSON line per tournament that either
checker refused, beside a copy of its TRF.
"""

import argparse
import json
import os
import subprocess
import sys
import time
from collections import Counter
from collections.abc import Iterator
from pathlib import Path

from data.pairings.random_tournaments import (
    MANDATORY_INDIVIDUAL_TIE_BREAKS as MANDATORY_INDIVIDUAL,
    MANDATORY_TEAM_TIE_BREAKS as MANDATORY_TEAM,
)

#: The criteria a run works through, one list per tournament in turn: the
#: points and one of the mandatory tie-breaks, so that a tournament the
#: other engine refuses names the criterion it disagreed on without any
#: untangling. The list is also one of the things the generator is
#: required to vary (question 24).
TIE_BREAK_LISTS = (
    ['PTS'],
    *([['PTS', acronym] for acronym in MANDATORY_INDIVIDUAL]),
)

#: Teams are ranked on their points first, as the individual lists are:
#: a standings definition naming only a tie-break is not one either
#: engine should be asked to read.
TEAM_TIE_BREAK_LISTS = tuple(['PTS', acronym] for acronym in MANDATORY_TEAM)


def check_one(
    seed: int,
    tie_breaks: list[str],
    directory: Path,
    team_event: bool = False,
    acceleration: bool = False,
) -> dict:
    """Generate one tournament and have both Gacrux checkers verify it."""
    from data.pairings.random_tournaments import (
        TournamentSettings,
        UnfinishedTournament,
        generate_tournament_file,
    )
    from tests.gacrux.harness import run_checker

    trf_path = directory / f'{seed}.trf'
    finding: dict = {'seed': seed, 'tie_breaks': tie_breaks}
    try:
        # Nothing but the criteria is stated, so every other parameter is
        # drawn per tournament (question 25).
        generate_tournament_file(
            TournamentSettings(
                tie_breaks=tie_breaks,
                team_event=team_event,
                acceleration=acceleration,
            ),
            trf_path,
            seed,
        )
    except UnfinishedTournament as error:
        # The checkers are asked about final standings, so a tournament that
        # could not be paired to its last round is left out and counted.
        finding['verdict'] = 'unfinished'
        finding['error'] = str(error)
        return finding
    except Exception as error:
        finding['verdict'] = 'generator-failed'
        finding['error'] = f'{type(error).__name__}: {error}'
        return finding
    refused = {}
    # The tie-break checker is told the tournament is a Swiss: it guesses a
    # round robin from the field and round counts of a file whose 192 code
    # it does not know, and an unplayed round of a round robin is not
    # evaluated the way Article 16 evaluates one of a Swiss. The pairing
    # checker takes no such option.
    for checker, args in (('pairingchecker', ()), ('tiebreakchecker', ('-s',))):
        run = run_checker(checker, trf_path, *args)
        if not run.ok:
            refused[checker] = {
                'status': run.status_code,
                'errors': run.errors[:5],
            }
    if refused:
        finding['verdict'] = 'refused'
        finding['refused'] = refused
        finding['trf'] = trf_path.read_text(encoding='ascii')
    else:
        finding['verdict'] = 'verified'
    trf_path.unlink(missing_ok=True)
    return finding


def already_done(out_path: Path) -> set[int]:
    """The seeds this worker has a finding for.

    A run interrupted mid-write leaves a partial last line, which is not
    a finding and is passed over: the seed it belongs to is checked again.
    """
    done: set[int] = set()
    if not out_path.exists():
        return done
    for line in out_path.read_text().splitlines():
        if not line.strip():
            continue
        try:
            done.add(json.loads(line)['seed'])
        except (json.JSONDecodeError, KeyError):
            continue
    return done


def run_worker(
    spec_path: Path,
    out_path: Path,
    resume: bool = False,
    team_event: bool = False,
    acceleration: bool = False,
) -> int:
    directory = out_path.parent
    done = already_done(out_path) if resume else set()
    with open(out_path, 'a' if resume else 'w', encoding='utf-8') as out:
        if resume and done:
            # A partial line from the interrupted write would otherwise be
            # continued by the next one.
            out.write('\n')
        for line in spec_path.read_text().splitlines():
            if not line.strip():
                continue
            seed_text, _, acronyms = line.partition(' ')
            if int(seed_text) in done:
                continue
            finding = check_one(
                int(seed_text),
                acronyms.split(','),
                directory,
                team_event,
                acceleration,
            )
            # Only a refusal is worth keeping: fifty thousand verified
            # tournaments are a number, not a list.
            out.write(
                json.dumps(
                    finding
                    if finding['verdict'] != 'verified'
                    else {'seed': finding['seed'], 'verdict': 'verified'}
                )
                + '\n'
            )
            out.flush()
    return 0


def run_coordinator(args: argparse.Namespace) -> int:
    from tests.gacrux.harness import gacrux_report_header

    report = Path(args.report).expanduser()
    report.mkdir(parents=True, exist_ok=True)
    catalogue = TEAM_TIE_BREAK_LISTS if args.team else TIE_BREAK_LISTS
    lists = [args.tie_breaks.split(',')] if args.tie_breaks else list(catalogue)
    jobs = max(1, args.jobs)
    print(gacrux_report_header())
    print(f'{args.count} tournaments, {jobs} workers, report in {report}')
    print('- criteria: ' + '; '.join(','.join(criteria) for criteria in lists))
    if args.resume:
        kept = sum(
            len(already_done(path)) for path in report.glob('work-*/findings.jsonl')
        )
        print(f'- resuming: {kept} already checked')

    started = time.perf_counter()
    processes = []
    for index in range(jobs):
        seeds = range(args.first_seed + index, args.first_seed + args.count, jobs)
        if not len(seeds):
            continue
        work = report / f'work-{index}'
        work.mkdir(exist_ok=True)
        spec_path = work / 'seeds.txt'
        spec_path.write_text(
            '\n'.join(f'{seed} {",".join(lists[seed % len(lists)])}' for seed in seeds)
        )
        processes.append(
            subprocess.Popen(
                [
                    sys.executable,
                    __file__,
                    '--worker',
                    str(spec_path),
                    '--out',
                    str(work / 'findings.jsonl'),
                    *(['--resume'] if args.resume else []),
                    *(['--team'] if args.team else []),
                    *(['--acceleration'] if args.acceleration else []),
                ],
                cwd=work,
                env=os.environ
                | {
                    # The data directory is the worker's own directory, so
                    # the workers neither share one nor go near tests/tmp.
                    'SC_MANUAL_PATH_USED': '1',
                    'PYTHONPATH': f'{Path.cwd() / "src"}:{Path.cwd()}',
                },
            )
        )
    for process in processes:
        process.wait()
    return summarise(report, args.count, time.perf_counter() - started)


def findings(report: Path) -> Iterator[dict]:
    for path in sorted(report.glob('work-*/findings.jsonl')):
        for line in path.read_text().splitlines():
            if line.strip():
                yield json.loads(line)


def summarise(report: Path, total: int, elapsed: float) -> int:
    verdicts: Counter[str] = Counter()
    refusals: Counter[str] = Counter()
    kept: list[dict] = []
    for finding in findings(report):
        verdicts[finding['verdict']] += 1
        if finding['verdict'] in ('verified', 'unfinished'):
            continue
        kept.append(finding)
        for checker, detail in (finding.get('refused') or {}).items():
            refusals[f'{checker} {detail["status"]}'] += 1
        if finding['verdict'] == 'generator-failed':
            refusals[finding['error'].split(':')[0]] += 1

    checked = sum(verdicts.values())
    lines = [
        '',
        f'{checked}/{total} tournaments generated and checked in {elapsed:.0f}s',
        f'  verified by both checkers  {verdicts["verified"]}',
        f'  refused                    {verdicts["refused"]}',
        f'  the generator failed on    {verdicts["generator-failed"]}',
        f'  unfinished, left out       {verdicts["unfinished"]}',
    ]
    for name, count in refusals.most_common():
        lines.append(f'    {name}: {count}')
    if kept:
        refused_dir = report / 'refused'
        refused_dir.mkdir(exist_ok=True)
        lines.append('')
        lines.append('Refused tournaments (first 20 by seed):')
        lines.extend(
            f'  seed {finding["seed"]} {finding["verdict"]}' for finding in kept[:20]
        )
        for finding in kept:
            if trf := finding.get('trf'):
                (refused_dir / f'{finding["seed"]}.trf').write_text(
                    trf, encoding='ascii'
                )
        lines.append(f'  TRFs written to {refused_dir}')
    text = '\n'.join(lines)
    print(text)
    (report / 'summary.txt').write_text(text + '\n')
    return 1 if kept else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument(
        'count', type=int, nargs='?', default=50000, help='how many tournaments'
    )
    parser.add_argument('--jobs', type=int, default=os.cpu_count() or 4)
    parser.add_argument('--report', default='cross-check', help='output directory')
    parser.add_argument(
        '--first-seed',
        type=int,
        default=0,
        help='the seed to start from, so a second run covers new tournaments',
    )
    parser.add_argument(
        '--tie-breaks',
        help='criteria for every tournament, comma-separated; the default '
        'works through a range of lists',
    )
    parser.add_argument(
        '--resume',
        action='store_true',
        help='carry on a run that was interrupted, keeping what the report '
        'directory already holds',
    )
    parser.add_argument(
        '--team',
        action='store_true',
        help='generate team tournaments and rank them on the team column '
        'of the mandatory tie-breaks',
    )
    parser.add_argument(
        '--acceleration',
        action='store_true',
        help='pair the individual tournaments with the Baku acceleration',
    )
    parser.add_argument('--worker', help=argparse.SUPPRESS)
    parser.add_argument('--out', help=argparse.SUPPRESS)
    args = parser.parse_args()
    if args.worker:
        return run_worker(
            Path(args.worker), Path(args.out), args.resume, args.team, args.acceleration
        )
    return run_coordinator(args)


if __name__ == '__main__':
    sys.exit(main())
