"""Generate tournaments and check them, in bulk.

The check-list asks (C.04.A Annex 3, question 33) for at least 50 000
random tournaments generated by each engine's generator and verified by
the other engine's checker. This is our side of that: the generator
writes them, and the checker reads each one back, re-pairing every round
and recomputing the standings from the tie-breaks the file names.

Our checker passing our own tournaments proves only that the two agree,
which is why question 33 asks for the other engine as well. What a run
here does catch is the two of them disagreeing with each other -- a
tournament we write and then refuse is a defect on one side or the other,
and there is no third party to blame.

    PYTHONPATH=src:. ./venv/bin/python scripts/fide/generate_and_check_tournaments.py 500
"""

import sys
from pathlib import Path

from common import TMP_DIR
from common.logger import print_interactive_error, print_interactive_info
from data.pairings.checkers import BbpPairingsChecker, TournamentCheck
from data.pairings.random_tournaments import TournamentSettings

#: The criteria a run works through when none are named, one list per
#: tournament in turn. A run that ranked every tournament the same way
#: would leave the standings checked against one set of criteria only,
#: and the tie-break list is one of the things the generator is required
#: to vary (question 24).
TIE_BREAK_LISTS = (
    ['PTS'],
    ['PTS', 'BH/C1'],
    ['PTS', 'BH/C1', 'SB'],
    ['PTS', 'BH/M1', 'SB', 'ARO'],
    ['PTS', 'DE', 'BH', 'WIN'],
    ['PTS', 'SB', 'KS', 'TPR'],
    ['PTS', 'FB/C1', 'AOB', 'BPG'],
    ['PTS', 'BH/C2/P', 'SB/C1', 'PS'],
)


def main(
    count: int,
    seed: int | None = None,
    tie_breaks: list[str] | None = None,
) -> int:
    """Generate *count* tournaments and check each one.

    ``tie_breaks`` is the criteria to rank them on, used for every
    tournament of the run. Left out, the run works through
    ``TIE_BREAK_LISTS`` instead, a tournament at a time, so that one run
    covers a range of them.
    """
    from data.pairings.random_tournaments import generate_tournament_file

    directory: Path = TMP_DIR / 'pairings_checker'
    directory.mkdir(exist_ok=True, parents=True)
    lists = [tie_breaks] if tie_breaks else list(TIE_BREAK_LISTS)
    checks: list[TournamentCheck] = []
    seeds: list[int] = []
    for index in range(max(count, 1)):
        tournament_file: Path = directory / f'{index:05d}.trf'
        # Nothing is stated but the criteria, so every other parameter is
        # drawn per tournament and the run covers a range of them
        # (question 25).
        settings = TournamentSettings(tie_breaks=lists[index % len(lists)])
        seeds.append(
            generate_tournament_file(
                settings,
                tournament_file,
                None if seed is None else seed + index,
            )
        )
        checks.append(BbpPairingsChecker.check_tournament(tournament_file))

    pairing_faults = [check for check in checks if check.diff]
    standings_faults = [check for check in checks if check.standings_diff]
    unchecked = [check for check in checks if check.unapplied_tie_breaks]
    print_interactive_info('Generated tournaments checked by our own checker')
    print_interactive_info(f'- Tournaments: {len(checks)}')
    print_interactive_info(
        f'- Players (min/max): '
        f'{min(check.player_count for check in checks)}/'
        f'{max(check.player_count for check in checks)}'
    )
    print_interactive_info(
        f'- Rounds (min/max): {min(check.rounds for check in checks)}/'
        f'{max(check.rounds for check in checks)}'
    )
    print_interactive_info(
        f'- Tournaments whose pairings the checker disputes: {len(pairing_faults)}'
    )
    print_interactive_info(
        f'- Tournaments whose standings the checker disputes: {len(standings_faults)}'
    )
    print_interactive_info(
        '- Criteria used: ' + '; '.join(','.join(criteria) for criteria in lists)
    )
    if unchecked:
        print_interactive_error(
            f'- Tournaments whose standings could not be checked: {len(unchecked)}'
        )
    for check, used in zip(checks, seeds, strict=True):
        if check.diff or check.standings_diff or check.unapplied_tie_breaks:
            print_interactive_error(f'  seed {used}: {check.name}')
    return 1 if pairing_faults or standings_faults or unchecked else 0


if __name__ == '__main__':
    # <count> [tie-breaks, comma-separated]
    sys.exit(
        main(
            int(sys.argv[1]) if len(sys.argv) > 1 else 10,
            tie_breaks=[
                acronym.strip() for acronym in sys.argv[2].split(',') if acronym.strip()
            ]
            if len(sys.argv) > 2
            else None,
        )
    )
