"""Generate tournaments and check them, in bulk.

The check-list asks (C.04.A Annex 3, question 33) for at least 50 000
random tournaments generated by each engine's generator and verified by
the other engine's checker. This is our side of that: the generator
writes them, and the checker reads each one back, re-pairing every round
and recomputing the standings from the tie-breaks the file names.

Our checker passing our own tournaments proves only that the two agree,
which is why question 33 asks for the other engine as well. What a run
here does catch is the two of them disagreeing with each other -- a
tournament we write and then refuse is a defect on one side or the other,
and there is no third party to blame.

    PYTHONPATH=src:. ./venv/bin/python scripts/fide/generate_and_check_tournaments.py 500
"""

import sys
from pathlib import Path

from common import TMP_DIR
from common.logger import print_interactive_error, print_interactive_info
from data.pairings.checkers import BbpPairingsChecker, TournamentCheck
from data.pairings.random_tournaments import TournamentSettings


def main(count: int, seed: int | None = None) -> int:
    """Generate *count* tournaments and check each one."""
    from data.pairings.random_tournaments import generate_tournament_file

    directory: Path = TMP_DIR / 'pairings_checker'
    directory.mkdir(exist_ok=True, parents=True)
    # Nothing is stated but the tie-breaks, so every other parameter is
    # drawn per tournament and the run covers a range of them (question
    # 25). The criteria are named so the standings have something to be
    # checked against.
    settings = TournamentSettings(tie_breaks=['PTS', 'BH/C1', 'SB'])
    checks: list[TournamentCheck] = []
    seeds: list[int] = []
    for index in range(max(count, 1)):
        tournament_file: Path = directory / f'{index:05d}.trf'
        seeds.append(
            generate_tournament_file(
                settings,
                tournament_file,
                None if seed is None else seed + index,
            )
        )
        checks.append(BbpPairingsChecker.check_tournament(tournament_file))

    pairing_faults = [check for check in checks if check.diff]
    standings_faults = [check for check in checks if check.standings_diff]
    unchecked = [check for check in checks if check.unapplied_tie_breaks]
    print_interactive_info('Generated tournaments checked by our own checker')
    print_interactive_info(f'- Tournaments: {len(checks)}')
    print_interactive_info(
        f'- Players (min/max): '
        f'{min(check.player_count for check in checks)}/'
        f'{max(check.player_count for check in checks)}'
    )
    print_interactive_info(
        f'- Rounds (min/max): {min(check.rounds for check in checks)}/'
        f'{max(check.rounds for check in checks)}'
    )
    print_interactive_info(
        f'- Tournaments whose pairings the checker disputes: {len(pairing_faults)}'
    )
    print_interactive_info(
        f'- Tournaments whose standings the checker disputes: {len(standings_faults)}'
    )
    if unchecked:
        print_interactive_error(
            f'- Tournaments whose standings could not be checked: {len(unchecked)}'
        )
    for check, used in zip(checks, seeds, strict=True):
        if check.diff or check.standings_diff or check.unapplied_tie_breaks:
            print_interactive_error(f'  seed {used}: {check.name}')
    return 1 if pairing_faults or standings_faults or unchecked else 0


if __name__ == '__main__':
    sys.exit(main(int(sys.argv[1]) if len(sys.argv) > 1 else 10))
