"""The tournaments the Gacrux checks run over, and how each is brought
into an event of its own.

Three families:

- the JSON fixtures in ``tests/json`` (the TEC tie-break exercises among
  them), imported the way the tie-break tests import them;
- the TRF files in ``tests/trf``, ``tests/trf/gacrux`` (tournaments
  generated by Gacrux) and ``tests/unit/tournament_importers``, imported
  and exported back, which exercises the importer as well;
- the example events shipped in ``examples/events``, one entry per
  tournament they hold.
"""

import contextlib
import shutil
import sqlite3
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from pathlib import Path

from common import BASE_DIR, EXAMPLE_EVENTS_DIR
from data.event import Event
from data.input_output.tournament_importer_options import FileOption
from data.input_output.trf.trf_importer import TrfTournamentImporter
from data.loader import EventLoader
from data.tournament import Tournament
from database.sqlite.event.event_database import EventDatabase
from tests.test_config import TestUtils
from utils.enum import EventType

JSON_DIR = BASE_DIR / 'tests' / 'json'
TRF_DIRS = (
    BASE_DIR / 'tests' / 'trf',
    BASE_DIR / 'tests' / 'trf' / 'gacrux',
    BASE_DIR / 'tests' / 'unit' / 'tournament_importers',
)


@dataclass(frozen=True)
class TournamentSource:
    """One tournament to check: its test id and how to load it."""

    id: str
    #: Creates the event ``uniq_id`` holding the tournament and returns
    #: both: a Tournament holds its event weakly, so the event has to be
    #: kept alongside for as long as the tournament is read.
    load: Callable[[str], tuple[Event, Tournament]]

    def __str__(self) -> str:
        return self.id


class LoadedTournament:
    """A tournament in an event created for one test, deleted with it."""

    def __init__(self, source: TournamentSource, suffix: str = '') -> None:
        self.source = source
        self.uniq_id = 'gacrux-' + ''.join(
            character if character.isascii() and character.isalnum() else '-'
            for character in source.id + suffix
        )
        try:
            self.event, self.tournament = source.load(self.uniq_id)
        except Exception:
            with contextlib.suppress(Exception):
                self.delete()
            raise

    def delete(self) -> None:
        TestUtils.delete_event(self.uniq_id)


def _reload(uniq_id: str) -> Event:
    EventLoader.unload_event(uniq_id)
    return EventLoader().load_event(uniq_id)


def _json_source(json_path: Path) -> TournamentSource:
    def load(uniq_id: str) -> tuple[Event, Tournament]:
        TestUtils.create_event(uniq_id)
        TestUtils.create_tournament(uniq_id, 'tournament', json_file=json_path.stem)
        event = _reload(uniq_id)
        return event, event.tournaments_by_name['tournament']

    return TournamentSource(f'json/{json_path.stem}', load)


def _trf_source(trf_path: Path) -> TournamentSource:
    def load(uniq_id: str) -> tuple[Event, Tournament]:
        overrides = {'event_type': EventType.TEAM} if _is_team_trf(trf_path) else None
        TestUtils.create_event(uniq_id, overrides=overrides)
        importer = TrfTournamentImporter([FileOption(trf_path)])
        tournament_id = importer.load_tournament(EventLoader().load_event(uniq_id))
        event = _reload(uniq_id)
        return event, event.tournaments_by_id[tournament_id]

    directory = trf_path.parent.name
    return TournamentSource(f'trf/{directory}/{trf_path.stem}', load)


def _is_team_trf(trf_path: Path) -> bool:
    """Whether the file carries team records (TRF26 300, or the older 013),
    which only import into a team event."""
    with open(trf_path, encoding='latin-1') as file:
        return any(line.startswith(('300 ', '013 ')) for line in file)


def _example_source(sce_path: Path, tournament_id: int, name: str) -> TournamentSource:
    def load(uniq_id: str) -> tuple[Event, Tournament]:
        database = EventDatabase(uniq_id)
        database.file.unlink(missing_ok=True)
        shutil.copy(sce_path, database.file)
        event = _reload(uniq_id)
        return event, event.tournaments_by_id[tournament_id]

    relative = sce_path.relative_to(EXAMPLE_EVENTS_DIR).with_suffix('')
    return TournamentSource(f'example/{relative}/{name}', load)


def _example_tournaments(sce_path: Path) -> Iterator[tuple[int, str]]:
    """The (id, name) of every tournament in an example event, read
    straight from the file: the event is only opened, and migrated, by
    the test that checks one of them."""
    connection = sqlite3.connect(f'file:{sce_path}?mode=ro', uri=True)
    try:
        yield from connection.execute('SELECT id, name FROM tournament ORDER BY id')
    finally:
        connection.close()


def json_sources() -> list[TournamentSource]:
    return [_json_source(path) for path in sorted(JSON_DIR.glob('*.json'))]


def trf_sources() -> list[TournamentSource]:
    return [
        _trf_source(path)
        for directory in TRF_DIRS
        for path in sorted(directory.glob('*.trf'))
    ]


def example_sources() -> list[TournamentSource]:
    return [
        _example_source(path, tournament_id, name)
        for path in sorted(EXAMPLE_EVENTS_DIR.rglob('*.sce'))
        for tournament_id, name in _example_tournaments(path)
    ]


def all_sources() -> list[TournamentSource]:
    return json_sources() + trf_sources() + example_sources()
