from datetime import datetime
from pathlib import Path

from common.i18n import _, locales
from common.logger import print_interactive_info, print_interactive_success
from data.auth.actions import AuthActionCategory, AuthAction
from data.auth.managers import RoleManager
from data.auth.roles import Role


def main():
    generated_by: str = _('Generated by script {script_name} on {date}').format(
        script_name=Path(__file__).name,
        date=datetime.now().strftime('%Y-%m-%d %H:%M'),
    )
    print_interactive_info('Generating roles inheritance documentation...')
    for locale in locales:
        with open(
            output_file := Path(__file__).with_name(f'roles-inheritance-{locale}.md'),
            'wt',
        ) as output:
            print(
                '|'
                f' {_("Role").replace(" ", "<br/>")} |'
                f' {_("Scope").replace(" ", "<br/>")} |'
                f' {_("Sub roles").replace(" ", "<br/>")} |'
                f' {_("Inherited roles").replace(" ", "<br/>")} |'
                f' {_("Manageable roles").replace(" ", "<br/>")} |',
                file=output,
            )
            print('|-|:-:|:-:|:-:|:-:|', file=output)
            roles: list[Role] = RoleManager.objects()
            for role in roles:
                ordered_direct_sub_roles = [
                    r for r in roles if r.__class__ in role.direct_sub_roles()
                ]
                ordered_indirect_sub_roles = [
                    r
                    for r in roles
                    if r in role.sub_roles() and r not in ordered_direct_sub_roles
                ]
                direct_sub_roles_str: str = f'_{_("none")}_'
                if ordered_direct_sub_roles:
                    direct_sub_roles_str = '<br/>'.join(
                        r.short_name() for r in ordered_direct_sub_roles
                    )
                indirect_sub_roles_str: str = f'_{_("none")}_'
                if (
                    len(ordered_direct_sub_roles) + len(ordered_indirect_sub_roles)
                    == len(roles) - 1
                ):
                    indirect_sub_roles_str = f'_{_("all")}_'
                elif ordered_indirect_sub_roles:
                    indirect_sub_roles_str = '<br/>'.join(
                        r.short_name() for r in ordered_indirect_sub_roles
                    )
                manageable_roles_str: str = f'_{_("none")}_'
                ordered_manageable_roles: list[Role] = [
                    r for r in RoleManager.objects() if r in role.manageable_roles()
                ]
                if len(ordered_manageable_roles) == len(roles) - 1:
                    manageable_roles_str = f'_{_("all")}_'
                elif ordered_manageable_roles:
                    manageable_roles_str = '<br/>'.join(
                        r.short_name() for r in ordered_manageable_roles
                    )
                print(
                    f'|{role.short_name()}: {role.name}|{role.scope.name}|{direct_sub_roles_str}|{indirect_sub_roles_str}|{manageable_roles_str}|',
                    file=output,
                )
            print(f'\n_{generated_by}_', file=output)
        print_interactive_success(f'Roles inheritance written to {output_file}.')

    actions_by_category: dict[AuthActionCategory, list[AuthAction]] = {}
    for category in AuthActionCategory.categories():
        actions_by_category[category] = []
    for action in AuthAction.actions():
        actions_by_category[action.category].append(action)

    print_interactive_info('Generating permissions by role documentation...')
    for locale in locales:
        with open(
            output_file := Path(__file__).with_name(f'roles-permissions-{locale}.md'),
            'wt',
        ) as output:
            mark_ok = ':white_check_mark:'
            mark_ko = ':x:'
            mark_na = ':white_circle:'
            col1_size = max(len(action.name) for action in AuthAction.actions())
            col_size = max(
                max(len(role.short_name()) for role in roles),
                max(len(mark) for mark in (mark_ok, mark_ko, mark_na)) + 3,
            )  # 3 = len('(*)')

            def print_line(col1: str, cols: list[str], last_col: str):
                print(
                    '|'
                    f' {col1.ljust(col1_size)} |'
                    f' {" | ".join([col.ljust(col_size) for col in cols] + [last_col.ljust(col_size)])} |',
                    file=output,
                )

            def print_header(col1: str, last_col: str):
                print_line(
                    col1, [r.short_name().ljust(col_size) for r in roles], last_col
                )

            print_line(
                _('Permissions / Roles'),
                [
                    '',
                ]
                * len(roles),
                '',
            )
            print(
                f'|-{"-" * col1_size}-|{f":{'-' * col_size}:|" * (len(roles) + 1)}',
                file=output,
            )
            for category, actions in actions_by_category.items():
                print_header(category.name.upper(), f'_{_("none")}_')
                if category == AuthActionCategory.EVENTS_ACCESS:
                    print_line(
                        _('View public current events'),
                        [
                            mark_ok,
                        ]
                        + [
                            mark_na,
                        ]
                        * (len(roles) - 1),
                        f'{mark_ok}(*)',
                    )
                for action in actions_by_category[category]:
                    if category in [
                        AuthActionCategory.APPLICATION,
                        AuthActionCategory.EVENTS_ACCESS,
                    ]:
                        print_line(
                            action.name,
                            [
                                mark_ok
                                if action in roles[0].allowed_actions()
                                else mark_ko,
                            ]
                            + [
                                mark_na,
                            ]
                            * (len(roles) - 1),
                            mark_ko,
                        )
                    else:
                        print_line(
                            action.name,
                            [
                                (
                                    mark_ok
                                    if action in role.allowed_actions()
                                    else mark_ko
                                )
                                for role in roles
                            ],
                            mark_ko,
                        )
                if category == AuthActionCategory.ACCESS:
                    for role in roles:
                        print_line(
                            _('Give/take away role {role_short_name}').format(
                                role_short_name=role.short_name()
                            ),
                            [
                                (
                                    mark_ok
                                    if role in role2.manageable_roles()
                                    else mark_ko
                                )
                                for role2 in roles
                            ],
                            mark_ko,
                        )
            print(f'\n_{generated_by}_', file=output)
        print_interactive_success(f'Roles permissions written to {output_file}.')
    print_interactive_info('Done.')


if __name__ == '__main__':
    main()
