"""Scheveningen team-pairing system.

A Scheveningen is a match between exactly two teams in which every player
of one team meets every player of the other. On *n* boards that takes *n*
rounds; played twice (double round) it takes 2*n*, the second half
repeating the first in reverse order with the colours swapped, which is
what keeps anyone from having three of the same colour in a row.

The tables are the ones Otto Milvang recommends in "Scheveningen system"
(29 September 2022): those generated by Bousios Hristos's method, rather
than the older ad-hoc tables of the FIDE Arbiters' Manual. Milvang's
requirements, in priority order, are

1. every player of one team plays every player of the other;
2. no two players meet more than once;
3. the white/black difference is minimised — over the teams, over each
   player's whole match, over a player's consecutive games, and within
   a round.

Sizes where *n* divided by 4 leaves 2 (6, 10, 14…) admit no perfect
solution; 6 and 10 use the published hand-made tables below, and the
larger ones fall back to the generated compromise.

The board order is stable: board *j* always seats the *j*-th player of
team A, and team B rotates around it.
"""

from abc import ABC
from functools import cached_property, lru_cache
from typing import TYPE_CHECKING, override

from common.i18n import _
from data.pairings.engines import PairingEngine
from data.pairings.fixed_table import (
    FixedPairingTable,
    FixedTablePairingEngine,
    FixedTablePairingSystem,
    FixedTableVariation,
    TablePairing,
)
from data.pairings.settings import PairingSetting
from data.pairings.systems import SwissPairingSystem
from data.safety_mode import PairingAction, PermissionHandler
from utils.entity import EntityManager, EventBoundEntityManager

if TYPE_CHECKING:
    from data.event import Event
    from data.tournament import Tournament


# The two sizes with no generated solution, transcribed from Milvang's
# paper. The magnitude is the 1-based B-player, the sign its colour:
# positive means the B-player has white.
#
# 5 is deliberately *not* tabulated, though the paper prints a table for
# it that the rule below does not reproduce (board 3 of round 2 is
# A3-B4 here, B4-A3 there). The two are the same schedule with the same
# ten colour sequences, merely dealt to opposite sides of the match, and
# they tie on every requirement the paper states — so the generated one
# is used, which keeps every odd size under a single rule. Wikipedia,
# which carries the same table set, agrees with the generated one.
_SB6: tuple[tuple[int, ...], ...] = (
    (-1, 2, 3, -4, 5, -6),
    (2, -3, -5, 6, -4, 1),
    (-3, 5, 1, -2, -6, 4),
    (4, 6, -2, -1, 3, -5),
    (-5, -4, -6, 3, 1, 2),
    (6, -1, 4, 5, -2, -3),
)

_SB10: tuple[tuple[int, ...], ...] = (
    (-1, -2, -3, -4, 5, 6, 7, -8, 9, 10),
    (2, 1, 8, 3, -10, -5, -6, 4, -7, -9),
    (-3, -8, -4, -10, 6, 7, 9, -1, 2, 5),
    (4, 3, 10, -6, -7, 8, -5, -9, 1, -2),
    (-5, -4, 9, 7, 1, -10, 8, 2, -3, -6),
    (6, -7, -1, -9, -8, -2, 10, 5, 4, 3),
    (-7, 5, 2, 1, 4, 9, -3, -10, -6, -8),
    (8, 6, -5, -2, -9, -1, -4, 3, 10, 7),
    (-9, -10, -7, 5, 2, 3, 1, -6, -8, 4),
    (10, 9, 6, 8, -3, -4, -2, 7, -5, -1),
)


_TABULATED: dict[int, tuple[tuple[int, ...], ...]] = {6: _SB6, 10: _SB10}


def scheveningen_grid(players: int) -> tuple[tuple[tuple[int, bool], ...], ...]:
    """The raw schedule for *players* boards, indexed ``[round][board]``.

    Each cell is ``(b_index, b_is_white)``: the 0-based player of team B
    facing the board's team-A player, and which side has white. Board
    *j* always seats team A's *j*-th player, so only B moves.
    """
    if players < 2:
        raise ValueError(f'A Scheveningen needs at least 2 boards, got {players}.')
    half = players // 2
    # opponent[round][board] and b_is_white[round][board].
    opponent = [[0] * players for __ in range(players)]
    b_is_white = [[False] * players for __ in range(players)]

    if players in _TABULATED:
        table = _TABULATED[players]
        return tuple(
            tuple((abs(cell) - 1, cell > 0) for cell in table[round_])
            for round_ in range(players)
        )

    if players % 2:
        # Odd: a plain rotation, with the colours of each round derived
        # from the previous one so that they alternate per player.
        for round_ in range(players):
            for board in range(players):
                opponent[round_][board] = (round_ + board) % players
        for board in range(players):
            b_is_white[0][board] = board > half
        for round_ in range(1, players):
            for board in range(players):
                b_is_white[round_][board] = not b_is_white[round_ - 1][
                    (board + (round_ & 1)) % players
                ]
    else:
        # Two interleaved rotations of half the size: the top-left and
        # bottom-right quadrants rotate among the first half of each
        # team, the other two quadrants across the halves.
        for round_ in range(half):
            for board in range(half):
                rotated = (round_ + board) % half
                opponent[round_][board] = rotated
                opponent[round_][board + half] = rotated + half
                opponent[round_ + half][board] = rotated + half
                opponent[round_ + half][board + half] = rotated
        if players % 4 == 2:
            # No perfect colour scheme exists at these sizes: the two
            # middle rounds give the whole team one colour, the rest
            # split. (6 and 10 are tabulated above.)
            for round_ in range(players):
                for board in range(players):
                    if round_ in (half - 1, half) or board < half:
                        b_is_white[round_][board] = bool(round_ & 1)
                    else:
                        b_is_white[round_][board] = not (round_ & 1)
        else:
            # n divisible by 4: each round splits the boards evenly.
            for round_ in range(players):
                for board in range(players):
                    if board < half:
                        b_is_white[round_][board] = bool(round_ & 1)
                    else:
                        b_is_white[round_][board] = not (round_ & 1)

    return tuple(
        tuple(
            (opponent[round_][board], b_is_white[round_][board])
            for board in range(players)
        )
        for round_ in range(players)
    )


def _cell_to_pairing(board: int, b_index: int, b_is_white: bool) -> TablePairing:
    if b_is_white:
        return TablePairing(
            white_team='B',
            white_index=b_index + 1,
            black_team='A',
            black_index=board + 1,
        )
    return TablePairing(
        white_team='A',
        white_index=board + 1,
        black_team='B',
        black_index=b_index + 1,
    )


def _reversed_colours(pairing: TablePairing) -> TablePairing:
    return TablePairing(
        white_team=pairing.black_team,
        white_index=pairing.black_index,
        black_team=pairing.white_team,
        black_index=pairing.white_index,
    )


@lru_cache(maxsize=None)
def scheveningen_table(players_per_team: int, double_round: bool) -> FixedPairingTable:
    """The Scheveningen table for a match on *players_per_team* boards."""
    rounds: list[tuple[TablePairing, ...]] = [
        tuple(
            _cell_to_pairing(board, b_index, b_is_white)
            for board, (b_index, b_is_white) in enumerate(cells)
        )
        for cells in scheveningen_grid(players_per_team)
    ]
    if double_round:
        # The return match is played back to front with the colours
        # swapped, which is what avoids three same-coloured games in a
        # row at the turn.
        rounds += [
            tuple(_reversed_colours(pairing) for pairing in round_)
            for round_ in reversed(rounds)
        ]
    return FixedPairingTable(
        team_count=2,
        players_per_team=players_per_team,
        rounds=tuple(rounds),
        # 6, 10, 14… boards have no perfect solution; the tables used
        # there deliberately relax the colour balance.
        is_compromise=players_per_team % 4 == 2 and players_per_team > 2,
    )


class ScheveningenPairingSystem(FixedTablePairingSystem):
    @staticmethod
    def static_id() -> str:
        return 'SCHEVENINGEN'

    @staticmethod
    def static_name() -> str:
        return _('Scheveningen')

    @override
    def variation_manager(self, event: 'Event') -> EntityManager[FixedTableVariation]:
        return ScheveningenVariationManager(event)

    @property
    def pairing_buttons_template(self) -> str:
        return '/admin/pairings/swiss_pairing_buttons.html'

    @property
    @override
    def supports_complementary_pairings(self) -> bool:
        return False

    @property
    @override
    def predetermined_pairings(self) -> bool:
        # Who meets whom on which board is settled before the first move.
        return True

    @property
    @override
    def allow_rounds_update_once_started(self) -> bool:
        # The round count is the size of the match; changing it midway
        # would re-cut the table.
        return False

    @property
    @override
    def allow_player_addition_once_paired(self) -> bool:
        return False

    @cached_property
    def permission_handler(self) -> PermissionHandler[PairingAction]:
        return SwissPairingSystem().permission_handler

    def default_current_round(self, tournament: 'Tournament') -> int:
        return tournament.last_paired_round

    @override
    def get_table(
        self,
        team_count: int,
        players_per_team: int,
        tournament: 'Tournament | None' = None,
    ) -> FixedPairingTable | None:
        if team_count != 2 or players_per_team < 2:
            return None
        double_round = False
        if tournament is not None:
            variation = tournament.pairing_variation
            double_round = (
                isinstance(variation, ScheveningenVariation) and variation.double_round
            )
        return scheveningen_table(players_per_team, double_round)

    @override
    def supported_team_counts(self) -> tuple[int, ...]:
        # A Scheveningen is a match: exactly two teams.
        return (2,)


class ScheveningenEngine(FixedTablePairingEngine):
    @property
    @override
    def system(self) -> ScheveningenPairingSystem:
        return ScheveningenPairingSystem()

    @override
    def invalid_player_count_message(self, tournament: 'Tournament') -> str | None:
        if message := super().invalid_player_count_message(tournament):
            return message
        players = tournament.team_player_count or 0
        expected = tournament.pairing_variation.required_round_count(players)
        if expected is not None and tournament.rounds != expected:
            return _(
                'A Scheveningen on {boards} boards is played over {expected} '
                'rounds, so that every player meets every opponent.'
            ).format(boards=players, expected=expected)
        return None


class ScheveningenVariation(FixedTableVariation, ABC):
    @staticmethod
    def system() -> 'ScheveningenPairingSystem':
        return ScheveningenPairingSystem()

    @property
    def double_round(self) -> bool:
        """Whether the match is played twice, colours reversed."""
        return False

    @override
    def required_round_count(self, boards: int) -> int | None:
        if boards < 2:
            return None
        return boards * (2 if self.double_round else 1)

    @property
    def engine(self) -> PairingEngine:
        return ScheveningenEngine()

    @property
    def settings(self) -> list[PairingSetting]:
        return []

    @property
    def trf_encoded_type(self) -> str:
        # No FIDE TRF26 team code covers the Scheveningen.
        return 'CUSTOM_SCHEVENINGEN'


class StandardScheveningenVariation(ScheveningenVariation):
    @staticmethod
    def variation_id() -> str:
        return 'STANDARD'

    @staticmethod
    def static_name() -> str:
        return _('Scheveningen')


class DoubleScheveningenVariation(ScheveningenVariation):
    @staticmethod
    def variation_id() -> str:
        return 'DOUBLE'

    @staticmethod
    def static_name() -> str:
        return _('Double-round Scheveningen')

    @property
    @override
    def double_round(self) -> bool:
        return True


class ScheveningenVariationManager(EventBoundEntityManager[FixedTableVariation]):
    @override
    def entity_types(self) -> list[type[FixedTableVariation]]:
        return [StandardScheveningenVariation, DoubleScheveningenVariation]
