import sys
from pathlib import Path

from babel.messages import Catalog, Message
from babel.messages.frontend import CommandLineInterface
from babel.messages.pofile import read_po

from common.i18n import default_locale, set_locale, _, locale_localized_name
from common.logger import print_interactive_error, print_interactive_warning, print_interactive_info, \
    print_interactive_success
from common.papi_web_config import PapiWebConfig


def run_babel_command(
        babel_command: str,
        babel_args: list,
        quiet: bool = False,
):
    """ Run a Babel command using the command-line interface. """
    argv: list[str] = [sys.argv[0], ]
    if quiet:
        argv += ['-q', ]
    argv += [babel_command, ] + list(map(str, babel_args))  # map to ensure all args are passed as strings
    CommandLineInterface().run(argv)


class LocaleInfo:

    def __init__(
            self,
            id: str,
            locale_dir: Path,
            doc_dir: Path,
    ):
        self.id: str = id
        self.default: bool = id == default_locale
        self.locale_dir: Path = locale_dir
        self.po_file: Path = self.locale_dir / self.id / 'LC_MESSAGES' / 'messages.po'
        self.mo_file: Path = self.locale_dir / self.id / 'LC_MESSAGES' / 'messages.mo'
        self.doc_file: Path = doc_dir / f'i18n-{self.id}.md'
        self.messages: dict[str, Message] = {}
        self.empty_messages: dict[str, Message] = {}
        self.mandatory_messages: dict[str, Message] = {}
        self.empty_mandatory_messages: dict[str, Message] = {}
        self.flagged_messages: dict[str, dict[str, Message]] = {}

    def update(
            self,
            pot_file: Path,
    ):
        if not self.po_file.exists():
            print_interactive_info(f'- {self.po_file.parent}...')
            self.po_file.parent.mkdir(parents=True, exist_ok=True)
            run_babel_command(
                'init',
                [
                    f'--locale={self.id}',
                    f'--input-file={pot_file}',
                    f'--output-file={self.po_file}',
                ],
                quiet=True,
            )
        print_interactive_info(f'- {self.po_file}...')
        run_babel_command(
            'update',
            [
                f'--locale={self.id}',
                f'--output-dir={self.locale_dir}',
                f'--input-file={pot_file}',
                f'--output-file={self.po_file}',
                '--no-wrap',
                '--omit-header',
            ],
            quiet=True,
        )

    @staticmethod
    def escape_gh_md(string: str) -> str:
        return string.replace('*', '\*')

    def control(self):
        # Read the catalog.
        with open(self.po_file, 'rb') as f:
            catalog: Catalog = read_po(f)
        # Control all the messages.
        for msg in catalog:
            if msg.id:
                self.messages[msg.id] = msg
                if not msg.string:
                    self.empty_messages[msg.id] = msg
                    continue
                if msg.id.__contains__('***'):
                    self.mandatory_messages[msg.id] = msg
                    if not msg.string:
                        self.empty_mandatory_messages[msg.id] = msg
                        continue
                for flag in msg.flags:
                    if flag != 'python-format':
                        if not flag in self.flagged_messages:
                            self.flagged_messages[flag] = {}
                        self.flagged_messages[flag][msg.id] = msg

    def write_markdown(self):
        """ Write a markdown file showing the status of this translation. """
        set_locale(self.id)
        with open(self.doc_file, 'w', encoding='utf-8') as f:
            f.write('<!--\n    WARNING: DO NOT EDIT!\n    This file has been generated by script i18n_update.\n-->\n\n')
            f.write('**[{text}](../README.md)**\n\n'.format(text=_('Return to documentation summary')))
            f.write('# Papi-web - {text}\n\n'.format(text=_("English translation *** TRANSLATE ! ***")))
            file: str = '/'.join(reversed([self.po_file.name, ] + [d.name for d in self.po_file.parents[:3]]))
            f.write('- [{text}](../{file})\n\n'.format(
                text=_('View file {file}').format(file=file),
                file=file))
            f.write('## {text}\n\n'.format(text=_('Summary'), locale=self.id))
            f.write(f'| locale=`{self.id}` | {locale_localized_name(self.id)} |\n')
            f.write('|--|:--:|\n')
            f.write('|{text}|{num}/{total}|\n'.format(
                text=_('Empty mandatory messages'),
                num=len(self.empty_mandatory_messages), total=len(self.mandatory_messages)))
            f.write('|{text}|{num}/{total}|\n'.format(
                text=_('Empty messages'), num=len(self.empty_messages), total=len(self.messages)))
            for flag, messages in self.flagged_messages.items():
                f.write('|{text}|{num}/{total}|\n'.format(
                    text=_('Message flagged [{flag}]'.format(flag=flag)),
                    num=len(self.flagged_messages[flag]), total=len(self.messages)))
            f.write('\n')
            if self.empty_mandatory_messages:
                f.write('## {text} ({num})\n\n'.format(
                    text=_('Empty mandatory messages'), num=len(self.empty_mandatory_messages)))
                f.write('|{text1}|{text2}|\n'.format(text1=_('Message id'), text2=_('Locations')))
                f.write('|--|--|\n')
                for msg in self.empty_mandatory_messages.values():
                    if isinstance(msg.id, str):
                        text1: str = self.escape_gh_md(msg.id)
                    else:
                        text1: str = '**{s}** {st}<br/>**{p}** {pt}'.format(
                            s=_('Singular:'), st=self.escape_gh_md(msg.id[0]),
                            p=_('Plural:'), pt=self.escape_gh_md(msg.id[1]))
                    f.write('|{text1}|{text2}|\n'.format(
                        text1=text1,
                        text2='<br>'.join([f'{location[0]}:{location[1]}' for location in msg.locations])))
            if self.empty_messages:
                f.write('## {text} ({num})\n\n'.format(
                    text=_('Empty messages'), num=len(self.empty_messages)))
                if self.default:
                    f.write(_('Empty messages are not shown for the default language.') + '\n\n')
                else:
                    f.write('|{text1}|{text2}|\n'.format(text1=_('Message id'), text2=_('Locations')))
                    f.write('|--|--|\n')
                    for msg in self.empty_messages.values():
                        if isinstance(msg.id, str):
                            text1: str = self.escape_gh_md(msg.id)
                        else:
                            text1: str = '**{s}** {st}<br/>**{p}** {pt}'.format(
                                s=_('Singular:'), st=self.escape_gh_md(msg.id[0]),
                                p=_('Plural:'), pt=self.escape_gh_md(msg.id[1]))
                        f.write('|{text1}|{text2}|\n'.format(
                            text1=text1,
                            text2='<br>'.join([f'{location[0]}:{location[1]}' for location in msg.locations])))
                    f.write('\n')
            for flag in self.flagged_messages:
                f.write('## {text} ({num})\n'.format(
                    text=_('Message flagged [{flag}]').format(flag=flag), num=len(self.flagged_messages[flag])))
                f.write('|{text1}|{text2}|{text3}|\n'.format(
                    text1=_('Message id'), text2=_('Translation'), text3=_('Locations')))
                f.write('|--|--|--|\n')
                for msg in self.flagged_messages[flag].values():
                    if isinstance(msg.id, str):
                        text1: str = self.escape_gh_md(msg.id)
                        text2: str = self.escape_gh_md(msg.string)
                    else:
                        text1: str = '**{s}** {st}<br/>**{p}** {pt}'.format(
                            s=_('Singular:'), st=self.escape_gh_md(msg.id[0]),
                            p=_('Plural:'), pt=self.escape_gh_md(msg.id[1]))
                        text2: str = '**{s}** {st}<br/>**{p}** {pt}'.format(
                            s=_('Singular:'), st=self.escape_gh_md(msg.string[0]),
                            p=_('Plural:'), pt=self.escape_gh_md(msg.string[1]))
                    f.write('|{text1}|{text2}|{text3}|\n'.format(
                        text1=text1, text2=text2,
                        text3='<br>'.join([f'{location[0]}:{location[1]}' for location in msg.locations])))
                f.write('\n')
        print_interactive_info(f'  -  {self.doc_file}.')

    def print_summary(self):
        """ print a summary of the locale. """
        print_interactive_info(
            f'- Locale [{self.id}]{" (default)" if self.default else ""}: {"OK" if not self.empty_messages and not self.flagged_messages else ""}')
        if self.empty_mandatory_messages:
            print_interactive_error(f'  * Empty mandatory messages ({len(self.empty_mandatory_messages)})')
            for msg_id in self.empty_mandatory_messages:
                print_interactive_error(f'    - [{msg_id}]')
        if self.empty_messages:
            if self.id == default_locale:
                print_interactive_info(f'  * Empty messages ({len(self.empty_messages)}), not listed for the default locale.')
            else:
                print_interactive_warning(f'  * Empty messages ({len(self.empty_messages)})')
                for msg_id in self.empty_messages:
                    print_interactive_warning(f'    - [{msg_id}]')
        if self.flagged_messages:
            for flag, msgs in self.flagged_messages.items():
                print_interactive_warning(f'  * Messages flagged [{flag}] ({len(self.flagged_messages)})')
                for msg_id in msgs:
                    print_interactive_warning(f'    - [{msg_id}]')


class I18nHelper:

    def __init__(
            self,
            locales: list[str],
    ):
        """ The path of the i18n files (this script should be run from the dev root). """
        self.locales: list[str] = locales
        self.locale_dir: Path = PapiWebConfig.base_dir / 'locale'
        self.pot_file: Path = self.locale_dir / 'messages.pot'
        self.doc_dir: Path = PapiWebConfig.base_dir / 'docs'
        self.doc_file: Path = self.doc_dir / '86-i18n.md'
        print_interactive_info(f'Extracting i18n strings to {self.pot_file}...')
        self.extract()
        self.locale_infos: dict[str, LocaleInfo] = {
            locale: LocaleInfo(locale, self.locale_dir, self.doc_dir) for locale in locales
        }
        print_interactive_info('Updating PO files...')
        for locale_info in self.locale_infos.values():
            locale_info.update(self.pot_file)
        print_interactive_info('Compiling PO files...')
        self.compile()
        print_interactive_info('Inspecting PO files...')
        for locale_info in self.locale_infos.values():
            locale_info.control()
        print_interactive_info('Writing MD files...')
        self.write_markdown()
        self.print_summary()

    def extract(self, ):
        """ The configuration file used to extract stings from the source files. """
        extract_config_file: Path = PapiWebConfig.base_dir / 'utils' / 'babel.cfg'
        run_babel_command(
            'extract',
            [
                f'--mapping-file={extract_config_file}',
                f'--output-file={self.pot_file}',
                '--no-wrap',
                '--omit-header',
                '.',
            ],
            quiet=True,
        )

    def compile(self):
        run_babel_command(
            'compile',
            [
                '--use-fuzzy',
                f'--directory={self.locale_dir}',
            ],
            quiet=True,
        )

    def write_markdown(self):
        """ Update the i18n doc file with the status of the translations. """
        for locale_info in self.locale_infos.values():
            locale_info.write_markdown()
        set_locale(default_locale)
        lines_before_comment: list[str] = []
        lines_after_comment: list[str] = []
        # Read the lines until the expected comment is found
        with open(self.doc_file, 'rt', encoding='utf-8') as f:
            comment: str = '<!-- DO NOT EDIT! (START) -->'
            comment_found: bool = False
            for line in f:
                lines_before_comment.append(line)
                if line.startswith(comment):
                    comment_found = True
                    break
            if not comment_found:
                print_interactive_error(f'Could not edit [{self.doc_file}] (comment [{comment}] not found).')
                return
            comment: str = '<!-- DO NOT EDIT! (END) -->'
            comment_found: bool = False
            for line in f:
                if line.startswith(comment):
                    comment_found = True
                if comment_found:
                    lines_after_comment.append(line)
            if not comment_found:
                print_interactive_error(f'Could not edit [{self.doc_file}] (comment [{comment}] not found).')
                return
        with open(self.doc_file, 'w', encoding='utf-8') as f:
            for line in lines_before_comment:
                f.write(line)
            f.write('| Translations | ' + ' | '.join([
                locale_localized_name(locale) for locale in self.locales
            ]) + ' |\n')
            f.write('|--|' + (':--:|' * len (self.locales)) + '\n')
            f.write('| Locale | ' + ' | '.join([
                f'`{locale}`' for locale in self.locales
            ]) + ' |\n')
            f.write('| Empty mandatory messages | ' + ' | '.join([
                f'{len(locale_info.empty_mandatory_messages)}/{len(locale_info.mandatory_messages)}'
                for locale_info in self.locale_infos.values()
            ]) + ' |\n')
            f.write('| Empty messages | ' + ' | '.join([
                f'{len(locale_info.empty_messages)}/{len(locale_info.messages)}'
                for locale_info in self.locale_infos.values()
            ]) + ' |\n')
            f.write('| Details | ' + ' | '.join([
                f'[{locale_info.doc_file.name}]({locale_info.doc_file.name})'
                for locale_info in self.locale_infos.values()
            ]) + ' |\n')
            f.write('| PO file | ' + ' | '.join([
                f'[{locale_info.po_file.name}](' \
                + '/'.join(reversed([locale_info.po_file.name, ] + [d.name for d in locale_info.po_file.parents[:3]])) \
                + ')'
                for locale_info in self.locale_infos.values()
            ]) + ' |\n')
            flags: list[str] = []
            for locale in self.locale_infos:
                for flag in self.locale_infos[locale].flagged_messages:
                    if flag not in flags:
                        flags.append(flag)
            for flag in flags:
                f.write(f'| Message flagged [{flag}] | ' + ' | '.join([
                    f'{len(self.locale_infos[locale].flagged_messages[flag]) if flag in self.locale_infos[locale].flagged_messages else 0}/{len(self.locale_infos[locale].messages)}'
                    for locale in self.locales
                ]) + ' |\n')
            for line in lines_after_comment:
                f.write(line)
        print_interactive_info(f'  -  {self.doc_file}.')

    def print_summary(self):
        """ Print a summary of all the locales. """
        for locale_info in self.locale_infos.values():
            locale_info.print_summary()

    @property
    def perfect(self) -> bool:
        perfect: bool = True
        for locale_info in self.locale_infos.values():
            if locale_info.empty_mandatory_messages:
                print_interactive_error('Mandatory translations are missing.')
                perfect = False
                break
        for locale_info in self.locale_infos.values():
            if not locale_info.default and locale_info.empty_messages:
                print_interactive_warning('Translations are missing.')
                perfect = False
                break
        for locale_info in self.locale_infos.values():
            if locale_info.flagged_messages:
                print_interactive_warning('Translations are flagged.')
                perfect = False
                break
        if perfect:
            print_interactive_success('Translations seem perfect.')
        return perfect


def main():
    """ PO and MO files are automatically created from this list; to add a new locale, add it to the list. """
    locales: list[str] = ['en', 'fr', ]

    _ = I18nHelper(locales).perfect


if __name__ == '__main__':
    main()
